### ISSUE TITLE
Make the loader importable by TS

### ISSUE THREAD

**Issue by rorticus** [dojo/loader#108]
Right now TS won't import the loader because it does not provide any typings. The way in which you can use the module from Node is a little wonky,

```ts
import { RootRequire } from '@dojo/interfaces/loader';
const dojoRequire: RootRequire = require('@dojo/loader');

dojoRequire(...);
```

It'd much more convenient to use it like any other module,

```ts
import dojoRequire from '@dojo/loader';

dojoRequire(...);
```

**Comment by xblox** [comment]
@rorticus : so your steps are working for me. Last simple question about this loader: I don't know how to identify dojo's require correctly in my AMD server modules. Currently I am checking like this : var isDojoRequire = require.pack!=null but the pack attribute is gone. Can you recommend an attribute which is unique  (i have to compare against a require.js setup)? Thanks a million

**Comment by rorticus** [comment]
@xblox 
> so your steps are working for me. Last simple question about this loader: I don't know how to identify dojo's require correctly in my AMD server modules. Currently I am checking like this : var isDojoRequire = require.pack!=null but the pack attribute is gone. Can you recommend an attribute which is unique (i have to compare against a require.js setup)? Thanks a million

Here is a list of methods in `require`. Hopefully one of these does the trick?

https://github.com/dojo/interfaces/blob/master/src/loader.d.ts#L169-L206

**Comment by xblox** [comment]
@rorticus thanks a lot!

**Comment by rishson** [comment]
@rorticus anything further need to happen here, or OK to close?

**Comment by rorticus** [comment]
OK to close 😄
