### ISSUE TITLE
Support loading CSS modules in-browser

### ISSUE THREAD

**Issue by vansimke** [dojo/loader#120]
The loader should be able to load a CSS file properly without any pre-processing (e.g purely in-browser).

**Comment by kitsonk** [comment]
To be clear, there are two potential probelms to solve here:

- Loading of already transpiled `.m.css` files that are transpiled as part of a package.
- Creation of new `.m.css` files that maybe part of an example application.

Also, we should outline the process for changing styles, if there is no in browser transpilation, but it is arguable that telling a user to do one thing in an in-browser example and a different in a local development environment will only confuse users.

**Comment by rorticus** [comment]
Closing this as we've got something working for the demos,

https://plnkr.co/edit/9C8PhO5WTMgIi0RRgn92?p=preview

All we needed to do was add manually generated`.css.js` files that exported the class names from the CSS fles.
