### ISSUE TITLE
Package Manager Research

### ISSUE THREAD

**Issue by eheasley** [dojo/loader#23]
Explore using package manager config to configure the loader.

**Comment by kitsonk** [comment]
The scope of this is to determine if there is an easy way to "auto-magically" configure the loader (or provide a utility) that could provide a package map based on what is depended upon in either npm or bower.

**Comment by kitsonk** [comment]
This has been subsumed by [dojo/cli](https://github.com/dojo/cli) and associated commands.  Any work in "development tooling" would be addressed as a new issue.
