### ISSUE TITLE
Loader does not support data defines with absolute mids

### ISSUE THREAD

**Issue by devpaul** [dojo/loader#30]
I was recently working on an Intern 3.0 project that uses the Dojo 2.0.0-alpha.6 release, which appears similar in function to this loader. The problem I ran into was with nls modules built using the Dojo 1 build system with absolute mids. The build system would output nls modules that looked like:

```javascript
define("dojo/cldr/nls/number", { root:

//begin v1.x content
/// ...
```

Looking at loader's [current define definition](https://github.com/dojo/loader/blob/master/src/loader.ts#L13-L18) it appears that the loader does not support these built modules. With some amount of effort I was able to work around the issue in Intern by using the `useLoader` parameter and point it to Dojo 1's loader.

I imagine that Dojo 2's build system will use absolute mids when building into a single target and will need this functionality, or we should at least support this style of define for continuity.

**Comment by kfranqueiro** [comment]
Given what the [documentation](http://dojotoolkit.org/reference-guide/1.10/build/transforms/writeAmd.html#backcompat) says about Dojo 1's `insertAbsMids` build flag, I'm thinking there might not be much of a reason for Dojo 2's build process to do it.

That being said, it's still a part of the specification and we should probably support it, as it's always possible some library (or some build process) will do it.

**Comment by kitsonk** [comment]
Yes, I can't see us needing to support "built" absolute MIDs, it over complicates the build process.  Though obviously the intent is the loader should be able to support built layers as well.

**Comment by devpaul** [comment]
If this is a backcompat option and we are not supporting the `insertAbsMids` flag in the builds then technically we do not need to support this. However, it will cause issues with legacy Dojo code. I'd like to get @csnover's opinion as Intern 3 currently uses the loader.

**Comment by csnover** [comment]
r.js built layers just contain multiple `define` calls with absolute module IDs. There are some other exceptional modules (jquery, underscore) that contain the third argument even though they aren’t built, so it’s necessary to support the three-argument form no matter what.

**Comment by edhager** [comment]
@devpaul, I thought we supported the factory parameter being an object.  I think it fell through the cracks when we were working on the functional tests.  It should work now.  Check out the new functional tests added.
