### ISSUE TITLE
Loader plugin config

### ISSUE THREAD

**Issue by cadorn** [dojo/loader#34]
In `requirejs` the plugin loader interface is:

```
define({
    load: function (name, req, onload, config) {
```

The dojo loader one is:
```
define({
    load: function (name, require, loaded) {
```

I need access to the `config` object in my plugin. The config object is the config passed to require during bootstrapping the loader.

Can you add something to the dojo loader plugin interface that will give me access to a config object I can set when bootstrapping the loader?

**Comment by kitsonk** [comment]
It is part of the [AMD spec](https://github.com/amdjs/amdjs-api/blob/master/LoaderPlugins.md#load-function-resourceid-require-load-config-), so we should add it.

**Comment by maier49** [comment]
The LoaderPlugin interface in loader.ts is defined as 
`export interface LoaderPlugin {`
`	dynamic?: boolean;`
`	load?: (resourceId: string, require: Require, load: (value?: any) => void, config?: Object) => void;`
`	normalize?: (moduleId: string, normalize: (moduleId: string) => string) => string;`
`}`

It looks like `load` already has an optional `config` parameter.

**Comment by kitsonk** [comment]
@maier49 but it doesn't look like the [loader passes it](https://github.com/dojo/loader/blob/37b5bfdc4e89e83f7d8b482478c716406f2ff309/src/loader.ts#L751) when it is called.

**Comment by Tomdye** [comment]
Implemented and written tests, however, this highlighted an issue with our loader related to config being set every time a call to `require` is made: https://github.com/dojo/loader/issues/48

The failing `merge` test made me think about how the plugin config would support these merged configs. Looks like the code needs to be revisited to allow any updated config to be merged with the config that we save and pass on to plugin load functions.

**Comment by Tomdye** [comment]
Have updated PR with merged saved config and added test

**Comment by Tomdye** [comment]
Having investigated this further, I am coming across difficulties / inconsistencies in passing the `config` object to the load function. I have looked at what `requireJS` does and it appears that it exposes the original `config` mixed with the entire internal `config`.

The requireJS step by step process when a new config is passed in is as follows:

1. Save the shims from the current saved `config`
2. Mixin `paths`, `bundles`, `config` and `map` from the new config into the old config
3. Overwrite any other config options
4. Merge shims then write to saved config
5. Update saves `paths` with `name` and package `location` by iterating over new `config.packages`
6. Update `config.pkgs` using `name` from current `config.package` iteration

Our process is not quite the same as this so ensuring that we can supply a matching config to plugins is not entirely straight forward.

Any advice?

**Comment by kitsonk** [comment]
Let's put it on hold for the time being.  As you point out, the way the config is currently stored in the dojo-loader isn't "clean" for offering up to plugins, as take what is there and fold, bend, mutilate and otherwise merge it.

@cadorn is your plugin publicly available?  What parts specifically are you needing?

The [common configuration](https://github.com/amdjs/amdjs-api/blob/master/CommonConfig.md) currently specifies some things, but it appears that while passing the config is specified to the plugin, it is mostly convention.

**Comment by Tomdye** [comment]
We can change the loader to store everything it gets passed and manipulates (same as requireJS) in a `config` object and will just pass that to plugins.
The plugins will likely need the normalized values anyway rather than the raw passed in ones. I'll follow the same pattern as described above.

**Comment by cadorn** [comment]
@kitsonk I am using it here: https://github.com/pinf/pinf-for-dojo/blob/master/pinf.require.js#L6

I need a way to set a config object that gets passed to the plugin here: https://github.com/pinf/pinf-for-dojo/blob/master/examples/HelloWorld/index.html#L13

I do not need any config from the loader other than the object I pass through.

Giving plugins access to the whole config of the loader (including other plugins) is not necessarily a good idea if you want to isolate the plugin API. Having to pass things specifically to each plugin and only what it needs can make things more future-proof and simpler to implement. Ideally the dojo loader will not need plugins to modify its internals other than to add per-file processors which should never need access to the internal config of the loader.

**Comment by Tomdye** [comment]
@cadorn looks like what I have proposed in the linked PR should do the trick then.
If I understand correctly, the config for specific plugins is to be passed via the `config` object within the main `config`.

ie.
``` javascript
require.config({
   baseUrl: '../',
   paths: {
      somepath: 'location'
   },
   config: {
      pinf: {
         somekey: somevalue
      }
   }
})
```

**Comment by Tomdye** [comment]
@cadorn code merged into master that should fix this. Please let us know if it does as you expected.
