### ISSUE TITLE
Test loader plugins

### ISSUE THREAD

**Issue by eheasley** [dojo/loader#4]
## Task
Write tests for text loader plugin. Also write a test plugin to test the plugin API

## Loader Functional Testing Pattern
Write loader tests as functional tests to provide a clean environment in which the loader can operate.  Whenever possible use the pattern outlined in [this wiki](../wiki/Loader Functional Testing Pattern) for inspecting test results.

**Comment by edhager** [comment]
Write an AMD plugin that loads text files:  `dojo/text!some/text/file.txt'

**Comment by edhager** [comment]
In the tests, test the text plugin and then write a dummy plugins that fully test the loader's AMD plugin API.
