### ISSUE TITLE
consider  about loading in nashorn or rhino?

### ISSUE THREAD

**Issue by taoqf** [dojo/loader#40]
i am using nashorn with dojo loader 1.10.4

**Comment by kitsonk** [comment]
We should also investigate the state of play of Chakra/Node and see if there are any challenges/impacts to the loader working under that.

**Comment by Tomdye** [comment]
@taoqf do you have an example of how you are using Nashorn and an `amd` module loader please?
I'm not very familiar with Nashorn. Did some research / experimenting yesterday and have seen that there are two ways to use it:

1. via the `jjs` command line interface
2. via `ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");` within standard java code.

It looks like `requireJs` operates the first way with `r.js` enabling rhino / nashorn AMD loading and has separate modules / code for each environment.

<pre>
# Calling r.js to optimize a project using the build config in build.js
jjs -scripting path/to/r.js -- -o build.js

# Calling r.js to run AMD modules, where the main app program is main.js
jjs -scripting path/to/r.js -- main.js
</pre>

**Comment by taoqf** [comment]
@Tomdye it is same between jjs and java code way.
besides, i do not want use amd in nashorn , and i do not think it a good way except the coding style is much like browser style, like dojo1.x and r.js.
i do not have a good example on github now.
it is just like the example dojo1.x use for nodejs except loading dojo.js using the global function `load` instead of `require`

**Comment by Tomdye** [comment]
@taoqf the PR that adds `nashorn` support has been merged into master, why don't you give it a try and see if it works for you. Thanks
