### ISSUE TITLE
Use dojo/loader as the loader for Intern

### ISSUE THREAD

**Issue by dylans** [dojo/loader#49]
As a way to prove that we have a sufficiently robust loader, we want to test replacing Intern's use of dojo/dojo2's loader with this repo. Intern has a sufficient number of interesting loader use cases to hopefully catch other issues or things we haven't considered.

**Comment by Tomdye** [comment]
You want me to crack on with this tomorrow?

**Comment by dylans** [comment]
I'll let @kitsonk prioritize things, but I would suggest we tackle this after we feel that the loader is in sufficient shape with our known issues and PRs.

**Comment by Tomdye** [comment]
Much less code to change the default than I thought there'd be. PR raised

**Comment by dylans** [comment]
And all of the self-tests pass? Interesting that it was that easy. Be sure to have @kitsonk and @jason0x43 scrutinize the PR when they have time.

**Comment by Tomdye** [comment]
Have already spoken with Jason, the self-tests pass and the loader tests pass using the 'new' intern setup.

**Comment by jason0x43** [comment]
Note that the self tests do not exercise the code in a way that will use the new loader. You might do better to treat the loader like any other external loader and swap it in at runtime using the `loaders` config property.

**Comment by Tomdye** [comment]
So I should do that for the self test config?

**Comment by Tomdye** [comment]
Cheers for the heads up @jason0x43 , getting errors in selfTest now that i'd updated the `selftest.intern.js` file to use `dojo-loader/loader`. I DID think that was seeming too easy!

**Comment by Tomdye** [comment]
PR updated, requires changes to core, 2 pr's open at present.

**Comment by agubler** [comment]
I think that this should be tracked against intern rather than dojo loader.
