### ISSUE TITLE
Test loader CSP compliance

### ISSUE THREAD

**Issue by eheasley** [dojo/loader#5]
## Task

Write tests that confirm the loader's compliance with the browser's content security policy (CSP).
## Loader Functional Testing Pattern

Write loader tests as functional tests to provide a clean environment in which the loader can operate.  Whenever possible use the pattern outlined in [this wiki](../wiki/Loader Functional Testing Pattern) for inspecting test results.

**Comment by msssk** [comment]
I added CSP tests:
https://github.com/dojo/loader/compare/master...msssk:csp-tests

Ed, should I PR this branch, or hang onto it until we can add `dojo-core` as a normal `devDependency` (right now it's an [npm linked package](https://docs.npmjs.com/cli/link).

**Comment by msssk** [comment]
It occurs to me that since the CSP tests now have their own HTTP server, we should probably configure the server to send CSP headers (right now CSP is being enabled in the test pages using a `meta` tag).

**Comment by rorticus** [comment]
CSP tests from https://github.com/dojo/loader/pull/104 merged.
