### ISSUE TITLE
Update use of runInThisContext

### ISSUE THREAD

**Issue by jason0x43** [dojo/loader#57]
Since 0.12.0 (0.11.7, really), `vm.runInThisContext` has used an [`options` object](https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options) for its second argument. The loader should probably use that format, which would also allow it to set the `displayErrors` flag to improve syntax error output.

**Comment by kitsonk** [comment]
Related to theintern/intern#592

**Comment by Tomdye** [comment]
According to the linked spec @jason0x43 , the flag is `true` by default:
```
displayErrors: whether or not to print any errors to stderr, with the line of code that caused them highlighted, before throwing an exception. Will capture both syntax errors from compiling code and runtime errors thrown by executing the compiled code. Defaults to true.
```

**Comment by Tomdye** [comment]
perhaps the output is being trapped somehow or need to use the `reportModuleLoadError` functionality added previously to the loader.

https://github.com/dojo/loader/blob/master/src/loader.ts#L900

**Comment by jason0x43** [comment]
Good point. Need a test case...

**Comment by Tomdye** [comment]
@jason0x43 I've done some playing around with this and even with the object and a specified `fileName` attribute etc... it doesn't improve the output due to the default `displayErrors` value.
Basically, whatever you set the value to, the `intern` output is always the same and does not include the filename or the actual error location, I think `intern` may be swallowing this up somewhere?

**Comment by Tomdye** [comment]
@kitsonk I think this should be closed

**Comment by Tomdye** [comment]
PR Raised, issue is still with `intern` I believe as it is truncating the error output somewhere.

**Comment by kitsonk** [comment]
This appears to cause issues with Istanbul, where it doesn't recognise the file and therefore doesn't instrument it.  We are going to have to revert this (which I will do in a moment)
