### ISSUE TITLE
Report Node module loading errors?

### ISSUE THREAD

**Issue by novemberborn** [dojo/loader#76]
Errors thrown when using Node's `require` [are swallowed](https://github.com/dojo/loader/blob/959e402dd1c12d87cf630dd5ef88a06899fb6018/src/loader.ts#L865:L868):

``` js
            try {
                result = requireModule.nodeRequire(moduleId);
            }
            catch (error) {
                // If the Node.js 'require' function cannot locate a module it will throw "Error: Cannot find module"
                // Leave it to the caller of this function to handle a non-existent module
                // (and throw an error if desired)
                result = undefined;
            }
```

Unfortunately such errors can arise because:
1. the `moduleId` could not be located
2. the module itself has a dependency that cannot be resolved
3. the module had a syntax error
4. the module threw while being evaluated

It'd be really useful if the error could be included in the ["failed to load module" message](https://github.com/dojo/loader/blob/959e402dd1c12d87cf630dd5ef88a06899fb6018/src/loader.ts#L121). Currently the error message is only useful when dealing with the first scenario.

**Comment by taoqf** [comment]
i do not think it is needed in node.

**Comment by kitsonk** [comment]
It is if there are any requirements to support the AMD Plugin API under Node, which dojo-core internally requires and likely other packages will too.

There are two features that are not easily solved without some sort of loader, and both the NodeJS CommonJS loader and the SystemJS module loader don't currently provide this type of functionality in a way where we can write the code referencing a single module ID and have it work transparently across environments:

* Conditional loading of modules based on run-time feature detection or asserted build time features (dealt with by core/has).
* Loading of non-script resources in a way they can be consumed in a module (e.g. JSON, text, CSS, etc.)

It doesn't look like ES Module Loader will be supporting "plugins", which therefore means until we can find a way to provide these features in a transparent way, we will have to rely upon the dojo/loader in all environments.

**Comment by rorticus** [comment]
Merged with https://github.com/dojo/loader/pull/109
