### ISSUE TITLE
master build is failing

### ISSUE THREAD

**Issue by rishson** [dojo/loader#84]

**Comment by rishson** [comment]
FYI - [most recent failing build](https://travis-ci.org/dojo/loader/builds/128657261).

**Comment by kitsonk** [comment]
It looks like the conversion to the new packaging didn't work for the [loader](https://travis-ci.org/dojo/loader/builds/154252223).  @matt-gadd or @agubler should take a look.

**Comment by matt-gadd** [comment]
@kitsonk we did not release loader as part of the new packaging. it was noted in the status here: https://github.com/dojo/meta/issues/68

**Comment by agubler** [comment]
@kitsonk we haven't done loader yet, although I agree there seems to be an issue that's preventing the test failures to occur. This is the previous build with the long running test failures https://travis-ci.org/dojo/loader/builds/152952084 - I can take a look at why it is not liking the build pipeline but then the tests will fail again.

**Comment by agubler** [comment]
Basically now that we no longer have stopped moving the source maps to the `debug` directory as a result of the issues with relative mapping urls with TS2.0 the custom task in loader `uglify:dist` fails

**Comment by agubler** [comment]
And I seem to have inadvertently renamed the `ts` task for `esm`, to just `esm` so therefore the `dist_esm` task failed.
