### ISSUE TITLE
Improve dynamic loading of transpiled ES Modules with default exports

### ISSUE THREAD

**Issue by Tomdye** [dojo/loader#87]
In order to enable the loading of es6 modules we should add a check in the loader.
Transpilers such as TypeScript and Babel add `__esModule` meta to the module when it has been transpiled from ESM format. Adding a check for this would allow us to load these modules without the need to manually check for a `default` export

ie.
``` javascript
if (module.__esModule && module.default) {
	module = module.default;
}
```

**Comment by kitsonk** [comment]
I am not sure exactly what sort of behaviour this would add or change in the loader.  In the case of TypeScript and Babel, while the export that meta data, they still transpile other AMD/UMD/CJS modules to abstract the module from that.

My understanding is that this meta data is to inform the System loader how to load the transpiled module for consumption by other ESM modules.  I don't think we have plans for this loader to natively support loading ESM modules.

So what would this loader do differently when loading AMD modules (or delegating to the Node.js CJS loader)?

**Comment by matt-gadd** [comment]
what do you mean by `natively` supporting ESM modules? This is to add support for modules that are authored in ESM and transpiled to AMD/UMD/CJS. We are repeating this code wherever we are doing dynamic requires currently (example in app: https://github.com/dojo/app/blob/d5ee4705393e67497382d4942093fd22648e348c/src/lib/moduleResolver.ts#L21), and I imagine that people will want to author in ESM and load those with our loader no?

**Comment by kitsonk** [comment]
That is what I was looking for:

> We are repeating this code wherever we are doing dynamic requires currently

So it is "to enable dynamic loading of already transpiled ESM modules with a default export".

Are you confident that won't interfere with already transpiled modules which are emitted with that resolution?

For example, given this:

```typescript
import foo from 'foo';

foo.bar;
```

TypeScript emits this:

```javascript
define(["require", "exports", 'foo'], function (require, exports, foo_1) {
    "use strict";
    foo_1.default.bar;
});
```

Also, how would the user who is using require `require()` dynamically get access to other exports of a module when there is a default export?

**Comment by matt-gadd** [comment]
typescript works out the defaults at the point of importing, so I can't see what interference you're getting at?

yes, you would lose the ability to get at the other exports, but given `AMD` itself only supports a single export I think thats a fair and known limitation for a dynamic require? suggestions?

**Comment by matt-gadd** [comment]
or we could write a loader plugin, but plugins...:)

**Comment by kitsonk** [comment]
> typescript works out the defaults at the point of importing, so I can't see what interference you're getting at?

But if the loader loads `foo.js` that has been emitted like this:

```javascript
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = {
        bar: 'baz'
    };
});
```

But it gets remapped by the loader, then `foo_1.defaut.bar` won't work anymore, right?

> open to suggestions?

A helper function (similar to the one you linked to above) which can have a documented behaviour (and return a Promise).  Likely not in `dojo-loader` though... `dojo-core`?  An improvement upon [`load.ts`](https://github.com/dojo/core/blob/master/src/load.ts) which people should be using anyways when dynamically loading assets (though I am guilty of `require()` abuse too).

**Comment by kitsonk** [comment]
We should close this off, if there are any actions actually related to this.  As it stands, I don't see anything that should be modified in the loader, though maybe with `dojo-core/load` and we should address it as an issue there, but I may have the wrong end of the stick.

**Comment by matt-gadd** [comment]
@kitsonk agreed, i think if we address it it will be in `dojo-core/load`
