### ISSUE TITLE
Define the loader plugin API

### ISSUE THREAD

**Issue by edhager** [dojo/loader#9]
The current loader code uses the Dojo 1 loader plugin API.  RaveJS and systemjs use a loader lifecycle with more granular steps.  James Burke is experimenting with a loader lifecycle component: https://github.com/amodrojs/amodro-lifecycle

TODO: explore other plugin APIs and decide to either update the Dojo 2 loader API or stick with the Dojo 1 API.

**Comment by edhager** [comment]
We are going to stick with the current AMD plugin draft specification: https://github.com/amdjs/amdjs-api/blob/master/LoaderPlugins.md.  

We decided the state of the ES6 module specification does not yet allow an asynchronous CSP compliant loader to be written so the standalone Dojo loader is a continuation of the dojo/dojo2 AMD loader currently being used by Intern

**Comment by edhager** [comment]
More info on sticking with AMD for now... 

Here is a good post by James Burke that describes some of the problems with the ES6 module specification: http://jrburke.com/2015/02/13/how-to-know-when-es-modules-are-done/.  James does a good job explaining why we need to be able to load modules and get their dependencies without 

With AMD, we can make a single request for a module in an asynchronous CSP compliant fashion and determine the module's dependencies.  No calls to eval() are required and the code that defines the contents of the module does not execute until all of the dependencies are loaded.  To attempt that today with an ES6 module, you would have to first load the module using an XHR, scan the module code for dependencies and then load it again later using script injection after the dependencies have loaded.

**Comment by edhager** [comment]
More info  on sticking with the AMD plugin API...

Given we made the decision to stick with an AMD loader for now.  Colin Snover had already taken the Dojo 1 loader, removed the pre-AMD loading bits and converted it to typescript.  That loader supports the AMD plugin specification.  

The systemjs and RaveJS loaders are implemented to support loader plugins in the sense that you can write a plugin that changes the behavior of the loader.  Make the loader synchronous versus asynchronous, load different module formats, use transpilers and so on.  James Burke is working on a similar idea with his Amodro Lifecycle project: https://github.com/amodrojs/amodro-lifecycle.  In those projects, the loader has a more granular lifecycle than what the AMD plugin exposes:  normalize -> load versus normalize -> locate -> fetch -> transform -> instantiate.

There was talk of making the Dojo 2 AMD loader support a more granular AMD plugin  lifecycle.  It could make some of the AMD plugins simpler.  We decided against changing the AMD plugin for a couple reasons:
 1. Looking at the plugins we would initially write, it is hard to see a lot of benefit from a more granular lifecycle.
 1.  We decided to go with the refactored Dojo 1 loader to allow us to focus on other parts of Dojo 2 while the details of the ES6 module format are hammered out.  We will thoroughly test the loader and make it the smallest, fasted AMD loader it can be.  Trying to implement a loader plugin API similar to systemjs or RaveJS would mean starting over on a new loader which will not save time and duplicate the efforts of others.

**Comment by kitsonk** [comment]
My thoughts are to focus on a refactored Dojo 1 AMD loader (or for Dojo to abandon a loader in lieu of RequireJS).  We should limit dependency on AMD plugin API as much as possible for now until a more clear standard emerges for this type of functionality.  We should try to clearly document what type of loader functionality we are trying to implement and agree that there isn't another logical way of achieving this.  Like I would potentially question is the text plugin the best way of dynamically loading string resources? (It might be, but should be thought about)

**Comment by bryanforbes** [comment]
@kitsonk I've had similar thoughts and as I look at defining tasks and API for i18n, I think a promise-based API for loading language bundles makes more sense cross-platform (node vs. browser) than a plugin API. Is a plugin convenient? Sure, but it means that the package will require an extra loader be used in node. I also skipped using a loader plugin with [request](https://github.com/dojo/core/blob/master/src/request.ts#L43-L87) to make it easier to use core in node. To me, this approach makes more sense at this time.

**Comment by bryanforbes** [comment]
As a clarification, I'm not advocating removing plugins. I'm simply stating that since we're writing new APIs which can be redone to be async (such as widget lifecycle), the need for loader plugins to support sync APIs can be diminished.
