### ISSUE TITLE
cant unsubscribe from require.on('error')

### ISSUE THREAD

**Issue by xblox** [dojo/loader#93]
Hi,
there is currently no way to unsubscribe from require.on('error'). I assume that the current require:on/emit will be replaced with new things and so possibly this problem goes away by self.

This is the same problem as in the dojo-1 loader, making it hard and hacky to deal with module 404 errors (whereby dojo-1 keeps spitting errors), but also being able to turn the loader's require into a promise which triggers 'reject' for a mid 404 . Currently I end up with something pretty ugly like this: 

https://github.com/gbaumgart/dojo-experiments/blob/master/src/lib/testDojoPromisedLoader.html#L22 (doesn't event correctly but you get the idea what's needed). 

I asked already on SO how to clear dojo-1 loader errors, I've got told its by design. I just hope dojo-2 doesn't do the same thing....

thanks in advance. close this just if its out of your scope (being ok with dojo hacks since years...). 
g

**Comment by kitsonk** [comment]
Well, we didn't want to do a whole implementation of on/emit from the rest of Dojo 2, but yes, being able to unsubscribe is important.

**Comment by gbaumgart** [comment]
@kitsonk thanks a lot !

**Comment by edhager** [comment]
There is code in the dojo2 loader with a unit test that supports 'require.on('error').remove()'.  

Here is the test:
https://github.com/dojo/loader/blob/master/tests/unit/require.ts#L171-L189

**Comment by xblox** [comment]
Hey, thanks a lot! seems to work fine.
